"""add org logo_url

Revision ID: 95cef30ffe22
Revises: e16a5cadd9b4
Create Date: 2026-04-22 19:28:34.381466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95cef30ffe22'
down_revision: Union[str, Sequence[str], None] = 'e16a5cadd9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'logo_url')
    # ### end Alembic commands ###
