"""add user_agents

Revision ID: 9febe04c4fc2
Revises: fb3512a0825a
Create Date: 2026-04-22 15:33:21.691573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9febe04c4fc2'
down_revision: Union[str, Sequence[str], None] = 'fb3512a0825a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'agent_id', name='uq_user_agent')
    )
    op.create_index(op.f('ix_user_agents_agent_id'), 'user_agents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_user_agents_org_id'), 'user_agents', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_agents_user_id'), 'user_agents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_agents_user_id'), table_name='user_agents')
    op.drop_index(op.f('ix_user_agents_org_id'), table_name='user_agents')
    op.drop_index(op.f('ix_user_agents_agent_id'), table_name='user_agents')
    op.drop_table('user_agents')
    # ### end Alembic commands ###
